osx_image: xcode8.2
language: objective-c

install:
- gem install cocoapods
- ./install_swiftlint.sh

script:
- pod lib lint PGNParser.podspec
- swiftlint

- xcodebuild test -project PGNParser.xcodeproj -scheme PGNParser-iOS -destination 'platform=iOS Simulator,OS=10.1,name=iPhone 7'
- xcodebuild test -project PGNParser.xcodeproj -scheme PGNParser-macOS -destination 'platform=OS X,arch=x86_64'
- xcodebuild test -project PGNParser.xcodeproj -scheme PGNParser-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p'

- xcodebuild -project PGNParser.xcodeproj -scheme PGNParser-watchOS