osx_image: xcode11
language: objective-c

before_install:

- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install

install:
- ./install_swiftlint.sh

script:
- pod lib lint PGNParser.podspec

- swiftlint

- xcodebuild test -workspace PGNParser.xcworkspace -scheme PGNParser-iOS -destination 'platform=iOS Simulator,OS=latest,name=iPhone 8'
- xcodebuild test -workspace PGNParser.xcworkspace -scheme PGNParser-macOS -destination 'platform=macOS,arch=x86_64'
- xcodebuild test -workspace PGNParser.xcworkspace -scheme PGNParser-tvOS -destination 'platform=tvOS Simulator,OS=latest,name=Apple TV 4K'
- xcodebuild -workspace PGNParser.xcworkspace -scheme PGNParser-watchOS
